name: For each commit and PR build or push kernel
on:
  push:
    paths:
    - 'kernel/**'
  pull_request:
    paths:
    - 'kernel/**'

jobs:
  validation:
    runs-on: Ubuntu-20.04
    env:
      CGO_ENABLED: 0
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/heads/master') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ./hack/kernel-build-and-deploy.sh
